on:
  push:
    branches:
      - "master" # change to the branch you wish to deploy from
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      env:
        REACT_APP_OPENAI_API_KEY: "${{ secrets.REACT_APP_OPENAI_API_KEY }}"
        REACT_APP_OPENAI_ORG: "${{ secrets.REACT_APP_OPENAI_ORG }}"
      with:
        path: build # change to your build folder
      
